# Generated by Django 2.0.1 on 2018-07-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
