# Generated by Django 2.0.1 on 2018-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(choices=[('N', 'Nigeria'), ('uk', 'London'), ('usa', 'America')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unsure')], max_length=1),
        ),
    ]
