# Generated by Django 2.0.1 on 2018-07-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_auto_20180722_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='country',
        ),
    ]
